### PR TITLE
Create branch

### PR DESCRIPTION
**Pull request by Tchilo**

### CODE REVIEW

**Comment by Hector096** [comment]
Hi @Tchilo,

👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Required Changes ♻️
Check the comments under the review

1: Make sure you add node modules in your gitignore file.
2: I would recommend always using git-flow which will help the code reviewers to review your code well.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

N.A.
Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Comment by Hector096** [comment]
```
function iconButton(name) {
  const node = document.createElement('button');
  node.classList.add('icon-button');

  const icon = document.createElement('span');
  icon.innerText = name;
  icon.classList.add('material-icons', 'icon');

  node.appendChild(icon);
  return node;
}
```  

3: Make sure to use ES6 function syntax.

**Comment by Tchilo** [comment]
> Hi @Tchilo,
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> 1: Make sure you add node modules in your gitignore file.
> 2: Always use git-flow which will help the code reviewers to review your code well.

**Comment by Tchilo** [comment]
Thanks for the code review. 
I will make the changes 👍🏽

**Pull request closed without merging**
